# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Publish ticker options data

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-6'

permissions:
  contents: write

jobs:
  publish_options_data:
    runs-on: ubuntu-latest

    steps:
      - name: Setup repo
        uses: actions/checkout@v4
      - name: Put current date into a variable
        run: |
          echo "RELEASE_NAME=OPTIONS_DATA_$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Run job
        run: deno run --allow-all jobs/main-options-historical.ts
      - name: Commit data
        run: |
          git config --global user.name 'mnsrulz'
          git config --global user.email 'mnsrulz@users.noreply.github.com'
          git add --all
          git commit -am "data ingest"
          git push
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "temp/options-historical/*.json"
          tag: ${{ env.RELEASE_NAME }}
          commit: "main"
          allowUpdates: "true"