# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

# This workflow will install Deno then run `deno lint` and `deno test`.
# For more information see: https://github.com/denoland/setup-deno

name: Publish option snampshot images

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 1-6'

permissions:
  contents: write

jobs:
  publish_options_snapshot_images:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Setup repo
        uses: actions/checkout@v4      
      - name: Put current date into a variable
        run: |          
          echo "RELEASE_NAME=DEX_GEX_SNAPSHOT_$(date --rfc-3339=date)" >> ${GITHUB_ENV}
      - name: Install puppeteer deps
        run: sudo apt-get install -y ca-certificates fonts-liberation libasound2 libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgbm1 libgcc1 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release wget xdg-utils
      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - name: Setup puppeteer
        run: PUPPETEER_PRODUCT=chrome deno run -A https://deno.land/x/puppeteer@16.2.0/install.ts
      - name: Run
        run: deno run --allow-all jobs/main-options-snapshot.ts
      # - name: Upload artifacts 
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: uploads
      #     if-no-files-found: error
      #     path: ${{ github.workspace}}/temp/*.png
      #     retention-days: 1
      
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "temp/*.png"
          tag: ${{ env.RELEASE_NAME }}
          commit: "main"
          allowUpdates: "true"
      
      - name: Commit data
        run: |
          git config --global user.name 'mnsrulz'
          git config --global user.email 'mnsrulz@users.noreply.github.com'
          git add --all
          git commit -am "DEX_GEX_SNAPSHOT ingest"
          git push

          
      # - name: Release
      #   uses: softprops/action-gh-release@v1
      #   if: startsWith(github.ref, 'refs/tags/')
      #   with:
      #     name: ${{ steps.date.outputs.date }}
      #     files: |
      #       snapshots/*/*